import { Component, OnInit, OnDestroy, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Subscription } from 'rxjs';
import { MasterDataService } from '../../../../core/services/master-data.service';
import { 
  Department, 
  Designation, 
  Shift, 
  WorkLocation, 
  LeaveType, 
  Holiday 
} from '../../../../core/models/master-data.model';

@Component({
  selector: 'app-admin-master-data',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './master-data.html',
  styleUrls: ['./master-data.css']
})
export class MasterDataComponent implements OnInit, OnDestroy {
  activeTab: 'departments' | 'designations' | 'shifts' | 'locations' | 'leaves' | 'holidays' = 'departments';
  
  // Data lists
  departments: Department[] = [];
  designations: Designation[] = [];
  shifts: Shift[] = [];
  workLocations: WorkLocation[] = [];
  leaveTypes: LeaveType[] = [];
  holidays: Holiday[] = [];
  
  // Filtering & Search
  searchTerm = '';
  isDataLoading = false;

  // Add/Edit Modal State
  isModalOpen = false;
  modalMode: 'add' | 'edit' = 'add';
  selectedItemId: number | null = null;
  
  // Shared Form Model
  formModel: any = {};

  private subscriptions = new Subscription();

  constructor(
    private readonly masterDataService: MasterDataService,
    private readonly cdr: ChangeDetectorRef
  ) {
  }

  ngOnInit(): void {
    this.loadBootstrapData();
  }

  ngOnDestroy(): void {
    this.subscriptions.unsubscribe();
  }

  loadBootstrapData(): void {
    this.isDataLoading = true;
    this.subscriptions.add(
      this.masterDataService.getBootstrapData().subscribe({
        next: (res) => {
          this.departments = res.departments || [];
          this.designations = res.designations || [];
          this.shifts = res.shifts || [];
          this.workLocations = res.workLocations || [];
          this.leaveTypes = res.leaveTypes || [];
          this.holidays = res.holidays || [];
          this.isDataLoading = false;
          this.cdr.detectChanges();
        },
        error: (err) => {
          console.error('Error loading master data', err);
          this.isDataLoading = false;
          this.cdr.detectChanges();
        }
      })
    );
  }

  setActiveTab(tab: typeof this.activeTab): void {
    this.activeTab = tab;
    this.searchTerm = '';
    this.cdr.detectChanges();
  }

  // Getters for filtered data
  get filteredDepartments(): Department[] {
    const q = this.searchTerm.trim().toLowerCase();
    return this.departments.filter(d => 
      d.name.toLowerCase().includes(q) || (d.code && d.code.toLowerCase().includes(q))
    );
  }

  get filteredDesignations(): Designation[] {
    const q = this.searchTerm.trim().toLowerCase();
    return this.designations.filter(d => 
      d.name.toLowerCase().includes(q) || (d.code && d.code.toLowerCase().includes(q))
    );
  }

  get filteredShifts(): Shift[] {
    const q = this.searchTerm.trim().toLowerCase();
    return this.shifts.filter(s => 
      s.name.toLowerCase().includes(q)
    );
  }

  get filteredLocations(): WorkLocation[] {
    const q = this.searchTerm.trim().toLowerCase();
    return this.workLocations.filter(l => 
      l.name.toLowerCase().includes(q) || (l.address && l.address.toLowerCase().includes(q))
    );
  }

  get filteredLeaves(): LeaveType[] {
    const q = this.searchTerm.trim().toLowerCase();
    return this.leaveTypes.filter(l => 
      l.name.toLowerCase().includes(q) || l.code.toLowerCase().includes(q)
    );
  }

  get filteredHolidays(): Holiday[] {
    const q = this.searchTerm.trim().toLowerCase();
    return this.holidays.filter(h => 
      h.name.toLowerCase().includes(q) || h.date.includes(q)
    );
  }

  // Add/Edit Actions
  openAddModal(): void {
    this.modalMode = 'add';
    this.selectedItemId = null;
    
    // Initialize default forms based on active tab
    if (this.activeTab === 'departments') {
      this.formModel = { name: '', code: '', is_active: true };
    } else if (this.activeTab === 'designations') {
      this.formModel = { name: '', code: '', is_active: true };
    } else if (this.activeTab === 'shifts') {
      // code will be auto-generated by the service layer
      this.formModel = { name: '', code: '', start_time: '09:00', end_time: '18:00', is_active: true };
    } else if (this.activeTab === 'locations') {
      // code will be auto-generated by the service layer
      this.formModel = { name: '', code: '', address: '', is_active: true };
    } else if (this.activeTab === 'leaves') {
      this.formModel = { name: '', code: '', max_days: 12, is_active: true };
    } else if (this.activeTab === 'holidays') {
      this.formModel = { name: '', date: new Date().toISOString().slice(0, 10), is_active: true };
    }
    
    this.isModalOpen = true;
    this.cdr.detectChanges();
  }

  openEditModal(item: any): void {
    this.modalMode = 'edit';
    this.selectedItemId = item.id;
    this.formModel = { ...item };
    this.isModalOpen = true;
    this.cdr.detectChanges();
  }

  closeModal(): void {
    this.isModalOpen = false;
  }

  submitForm(): void {
    if (!this.formModel.name && this.activeTab !== 'holidays') {
      alert('Please fill in the required name field.');
      return;
    }

    if (this.activeTab === 'holidays' && (!this.formModel.name || !this.formModel.date)) {
      alert('Name and date are required for holidays.');
      return;
    }

    this.isDataLoading = true;
    let request$: any;

    if (this.modalMode === 'add') {
      if (this.activeTab === 'departments') {
        request$ = this.masterDataService.createDepartment(this.formModel);
      } else if (this.activeTab === 'designations') {
        request$ = this.masterDataService.createDesignation(this.formModel);
      } else if (this.activeTab === 'shifts') {
        request$ = this.masterDataService.createShift(this.formModel);
      } else if (this.activeTab === 'locations') {
        request$ = this.masterDataService.createWorkLocation(this.formModel);
      } else if (this.activeTab === 'leaves') {
        request$ = this.masterDataService.createLeaveType(this.formModel);
      } else {
        request$ = this.masterDataService.createHoliday(this.formModel);
      }
    } else {
      const id = this.selectedItemId!;
      if (this.activeTab === 'departments') {
        request$ = this.masterDataService.updateDepartment(id, this.formModel);
      } else if (this.activeTab === 'designations') {
        request$ = this.masterDataService.updateDesignation(id, this.formModel);
      } else if (this.activeTab === 'shifts') {
        request$ = this.masterDataService.updateShift(id, this.formModel);
      } else if (this.activeTab === 'locations') {
        request$ = this.masterDataService.updateWorkLocation(id, this.formModel);
      } else if (this.activeTab === 'leaves') {
        request$ = this.masterDataService.updateLeaveType(id, this.formModel);
      } else {
        request$ = this.masterDataService.updateHoliday(id, this.formModel);
      }
    }

    this.subscriptions.add(
      request$.subscribe({
        next: () => {
          this.isModalOpen = false;
          this.loadBootstrapData();
          alert(`Successfully ${this.modalMode === 'add' ? 'created' : 'updated'} record.`);
        },
        error: (err: any) => {
          this.isDataLoading = false;
          alert('Error updating master data: ' + (err.error?.detail || err.message));
          this.cdr.detectChanges();
        }
      })
    );
  }
}
