"""Add TimeOff System enhancements

Revision ID: 0ac6a61889e6
Revises: 0cc909ddb9d3
Create Date: 2026-05-05 17:46:11.243285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac6a61889e6'
down_revision: Union[str, Sequence[str], None] = '0cc909ddb9d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('timeoff_balance_hours', sa.Float(), nullable=True))
    op.add_column('timeoff_requests', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('timeoff_requests', sa.Column('end_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeoff_requests', 'end_time')
    op.drop_column('timeoff_requests', 'start_time')
    op.drop_column('employees', 'timeoff_balance_hours')
    # ### end Alembic commands ###
