"""Add TimeOffRequest and update Attendance model

Revision ID: 0cc909ddb9d3
Revises: 4c4777287636
Create Date: 2026-05-05 12:16:47.569421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cc909ddb9d3'
down_revision: Union[str, Sequence[str], None] = '4c4777287636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('total_working_minutes', sa.Integer(), nullable=True))
    op.add_column('attendance', sa.Column('grand_total_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'grand_total_minutes')
    op.drop_column('attendance', 'total_working_minutes')
    # ### end Alembic commands ###
