"""Add early punch in rules and manager approvals

Revision ID: 12f0873fcfad
Revises: fb2c3d4e5f60
Create Date: 2026-08-31 12:24:34.164713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12f0873fcfad'
down_revision: Union[str, Sequence[str], None] = 'fb2c3d4e5f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('approval_tasks_manager_reviewed_by_fkey'), 'approval_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'approval_tasks', 'users', ['manager_reviewed_by'], ['id'])
    op.add_column('attendance', sa.Column('early_arrival_minutes', sa.Integer(), nullable=True))
    op.add_column('attendance', sa.Column('late_minutes', sa.Integer(), nullable=True))
    op.add_column('attendance', sa.Column('punch_in_grace_minutes', sa.Integer(), nullable=True))
    op.add_column('attendance', sa.Column('early_punch_window_minutes', sa.Integer(), nullable=True))
    op.add_column('attendance', sa.Column('shift_grace_minutes', sa.Integer(), nullable=True))
    op.add_column('attendance', sa.Column('approved_early_minutes', sa.Integer(), nullable=True))
    op.add_column('attendance', sa.Column('unapproved_early_minutes', sa.Integer(), nullable=True))
    op.add_column('attendance', sa.Column('credited_work_start', sa.Time(), nullable=True))
    op.add_column('attendance', sa.Column('credited_work_end', sa.Time(), nullable=True))
    op.add_column('attendance', sa.Column('regular_work_minutes', sa.Integer(), nullable=True))
    op.add_column('attendance', sa.Column('approved_extra_minutes', sa.Integer(), nullable=True))
    op.add_column('attendance', sa.Column('early_approval_status', sa.String(length=20), nullable=True))
    op.add_column('attendance', sa.Column('early_approved_by', sa.Integer(), nullable=True))
    op.add_column('attendance', sa.Column('early_approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('attendance', sa.Column('early_approval_reason', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'attendance', 'users', ['early_approved_by'], ['id'])
    op.add_column('shifts', sa.Column('allow_early_punch_in', sa.Boolean(), nullable=True))
    op.add_column('shifts', sa.Column('early_coming_minutes', sa.Integer(), nullable=True))
    op.add_column('shifts', sa.Column('punch_in_grace_minutes', sa.Integer(), nullable=True))
    op.add_column('shifts', sa.Column('shift_grace_minutes', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_timeoff_requests_batch_id'), 'timeoff_requests', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeoff_requests_batch_id'), table_name='timeoff_requests')
    op.drop_column('shifts', 'shift_grace_minutes')
    op.drop_column('shifts', 'punch_in_grace_minutes')
    op.drop_column('shifts', 'early_coming_minutes')
    op.drop_column('shifts', 'allow_early_punch_in')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_column('attendance', 'early_approval_reason')
    op.drop_column('attendance', 'early_approved_at')
    op.drop_column('attendance', 'early_approved_by')
    op.drop_column('attendance', 'early_approval_status')
    op.drop_column('attendance', 'approved_extra_minutes')
    op.drop_column('attendance', 'regular_work_minutes')
    op.drop_column('attendance', 'credited_work_end')
    op.drop_column('attendance', 'credited_work_start')
    op.drop_column('attendance', 'unapproved_early_minutes')
    op.drop_column('attendance', 'approved_early_minutes')
    op.drop_column('attendance', 'shift_grace_minutes')
    op.drop_column('attendance', 'early_punch_window_minutes')
    op.drop_column('attendance', 'punch_in_grace_minutes')
    op.drop_column('attendance', 'late_minutes')
    op.drop_column('attendance', 'early_arrival_minutes')
    op.drop_constraint(None, 'approval_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('approval_tasks_manager_reviewed_by_fkey'), 'approval_tasks', 'users', ['manager_reviewed_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
