"""Add scheduled_start and scheduled_end to Attendance

Revision ID: 4b34ecaa7e70
Revises: 
Create Date: 2026-05-02 10:36:56.216188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b34ecaa7e70'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('scheduled_start', sa.Time(), nullable=True))
    op.add_column('attendance', sa.Column('scheduled_end', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'scheduled_end')
    op.drop_column('attendance', 'scheduled_start')
    # ### end Alembic commands ###
