"""Add task_description to Attendance

Revision ID: 4c4777287636
Revises: 4b34ecaa7e70
Create Date: 2026-05-02 10:51:25.716928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c4777287636'
down_revision: Union[str, Sequence[str], None] = '4b34ecaa7e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('task_description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'task_description')
    # ### end Alembic commands ###
