"""add_image_columns_to_attendance

Revision ID: 76531a90676c
Revises: feeff5054dc4
Create Date: 2026-05-23 13:27:19.779387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76531a90676c'
down_revision: Union[str, Sequence[str], None] = 'feeff5054dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('check_in_image', sa.String(), nullable=True))
    op.add_column('attendance', sa.Column('check_out_image', sa.String(), nullable=True))
    op.add_column('punch_logs', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('punch_logs', 'image')
    op.drop_column('attendance', 'check_out_image')
    op.drop_column('attendance', 'check_in_image')
    # ### end Alembic commands ###
