"""add_hardening_constraints

Revision ID: 9c76cbfeaf96
Revises: 099d48fab4c9
Create Date: 2026-07-07 11:05:41.480736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c76cbfeaf96'
down_revision: Union[str, Sequence[str], None] = '099d48fab4c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_attendance_employee_date', 'attendance', ['employee_id', 'date'])
    op.create_index('ix_timeoff_employee_date_status', 'timeoff_requests', ['employee_id', 'date', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timeoff_employee_date_status', table_name='timeoff_requests')
    op.drop_constraint('uq_attendance_employee_date', 'attendance', type_='unique')
    # ### end Alembic commands ###
