"""refactor_hr_users

Revision ID: decd7f6b966c
Revises: 0a535eb07231
Create Date: 2026-06-27 13:38:10.368422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'decd7f6b966c'
down_revision: Union[str, Sequence[str], None] = '0a535eb07231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_users', sa.Column('hr_settings', sa.String(), nullable=True))
    op.drop_constraint(op.f('hr_users_email_key'), 'hr_users', type_='unique')
    op.drop_index(op.f('ix_hr_users_hr_code'), table_name='hr_users')
    op.drop_column('hr_users', 'designation')
    op.drop_column('hr_users', 'hr_code')
    op.drop_column('hr_users', 'email')
    op.drop_column('hr_users', 'department')
    op.drop_column('hr_users', 'full_name')
    op.drop_column('hr_users', 'phone')
    op.drop_column('hr_users', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_users', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('hr_users', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('hr_users', sa.Column('full_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('hr_users', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('hr_users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('hr_users', sa.Column('hr_code', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('hr_users', sa.Column('designation', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_hr_users_hr_code'), 'hr_users', ['hr_code'], unique=True)
    op.create_unique_constraint(op.f('hr_users_email_key'), 'hr_users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('hr_users', 'hr_settings')
    # ### end Alembic commands ###
