"""add_enterprise_attendance_and_overtime

Revision ID: e3384280db78
Revises: 76531a90676c
Create Date: 2026-06-13 13:21:00.846687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3384280db78'
down_revision: Union[str, Sequence[str], None] = '76531a90676c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_views_id'), table_name='news_views')
    op.drop_table('news_views')
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.drop_table('news')
    op.add_column('attendance', sa.Column('checkout_source', sa.String(length=20), nullable=True))
    op.add_column('attendance', sa.Column('flags', sa.String(length=500), nullable=True))
    op.add_column('attendance', sa.Column('requires_regularization', sa.Boolean(), nullable=True))
    op.add_column('attendance', sa.Column('overtime_approved', sa.Boolean(), nullable=True))
    op.add_column('attendance', sa.Column('overtime_start', sa.Time(), nullable=True))
    op.add_column('attendance', sa.Column('overtime_end', sa.Time(), nullable=True))
    op.add_column('attendance', sa.Column('shift_end_reminder_sent', sa.Integer(), nullable=True))
    op.add_column('attendance', sa.Column('overtime_reminder_sent', sa.Integer(), nullable=True))
    op.add_column('attendance', sa.Column('overtime_extended', sa.Boolean(), nullable=True))
    op.alter_column('users', 'profile_image',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_image',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('attendance', 'overtime_extended')
    op.drop_column('attendance', 'overtime_reminder_sent')
    op.drop_column('attendance', 'shift_end_reminder_sent')
    op.drop_column('attendance', 'overtime_end')
    op.drop_column('attendance', 'overtime_start')
    op.drop_column('attendance', 'overtime_approved')
    op.drop_column('attendance', 'requires_regularization')
    op.drop_column('attendance', 'flags')
    op.drop_column('attendance', 'checkout_source')
    op.create_table('news',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('target_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('target_departments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('target_users', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('news_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('news_pkey'))
    )
    op.create_index(op.f('ix_news_id'), 'news', ['id'], unique=False)
    op.create_table('news_views',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('news_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('viewed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], name=op.f('news_views_news_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('news_views_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('news_views_pkey'))
    )
    op.create_index(op.f('ix_news_views_id'), 'news_views', ['id'], unique=False)
    # ### end Alembic commands ###
