"""update_notification_model

Revision ID: e950f75555ac
Revises: d576047fa37a
Create Date: 2026-06-30 12:58:04.961842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e950f75555ac'
down_revision: Union[str, Sequence[str], None] = 'd576047fa37a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('notifications', sa.Column('severity', sa.String(length=20), nullable=True))
    op.add_column('notifications', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('receiver_role', sa.String(length=50), nullable=True))
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('notifications', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notifications', sa.Column('notification_metadata', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'notification_metadata')
    op.drop_column('notifications', 'deleted_at')
    op.drop_column('notifications', 'updated_at')
    op.drop_column('notifications', 'receiver_role')
    op.drop_column('notifications', 'created_by')
    op.drop_column('notifications', 'employee_id')
    op.drop_column('notifications', 'severity')
    op.drop_column('notifications', 'category')
    # ### end Alembic commands ###
