"""add_location_to_punch_logs

Revision ID: feeff5054dc4
Revises: b1f6a9d4c2e3
Create Date: 2026-05-16 12:56:17.996015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feeff5054dc4'
down_revision: Union[str, Sequence[str], None] = 'b1f6a9d4c2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'total_worked_seconds',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('attendance', 'is_working',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('punch_logs', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('punch_logs', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('punch_logs', sa.Column('address', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('punch_logs', 'address')
    op.drop_column('punch_logs', 'longitude')
    op.drop_column('punch_logs', 'latitude')
    op.alter_column('attendance', 'is_working',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('attendance', 'total_worked_seconds',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
